package com.example.dhsrd.model;

public enum SrdType {
    CONTENTS, ABILITIES, ADVERSARIES, ANCESTRIES, ARMOR, COMMUNITIES, CONSUMABLES, DOMAINS, ENVIRONMENTS, FRAMES, ITEMS, CLASSES, SUBCLASSES,
    WEAPONS
}